version: '3.9'
services:
  postgres:
    image: postgres
    env:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=bank
  server: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -"5000:5000"
    environment:
      - DBSOURCE="postgresql://root:secret@postgresbank:5432/bank?sslmode=disable"